#!/usr/bin/bash
option(){
  xdotool search --all --name "RuneScape"
  xdotool search --classname "RuneScape"
}

find_Runescape(){
  pids=($(xdotool search --classname "RuneScape"))
  export Runescape=${pids[-1]}
}

all(){
  for i in "${pids[@]}"; do echo $i; done
}

get(){
  find_Runescape
  echo $Runescape
}
