#!/usr/bin/bash

# Desktop option
gnome(){
  export X=78
  export Y=109
}
lxqt(){
  export X=
  export Y=
}

gnome_right_half_screen(){
  export X=1004
  export Y=109
}

find_Runescape(){
  pids=($(xdotool search --classname "RuneScape"))
  export Runescape=${pids[-1]}
}

find_Runescape
xdotool windowmove $Runescape $X $Y
xdotool windowsize $Runescape $sizeX $sizeY
